-- AlterTable
ALTER TABLE "leave_policy_values" ADD COLUMN     "allowedContractTypes" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "baseDaysPerYear" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "bonusDaysPerCycle" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "bonusYearCycle" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "carryOverDays" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "joinDateCutoffDay" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN     "prorateByMonth" BOOLEAN NOT NULL DEFAULT true;
