export enum AppError {
  // Auth
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  AUTH_INVALID_TOKEN = 'AUTH_INVALID_TOKEN',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',

  // OT Plan
  OT_PLAN_NOT_FOUND = 'OT_PLAN_NOT_FOUND',
  OT_PLAN_INVALID_STATUS = 'OT_PLAN_INVALID_STATUS',
  OT_PLAN_FORBIDDEN = 'OT_PLAN_FORBIDDEN',

  // OT Ticket
  OT_TICKET_NOT_FOUND = 'OT_TICKET_NOT_FOUND',
  OT_TICKET_INVALID_STATUS = 'OT_TICKET_INVALID_STATUS',
  OT_TICKET_FORBIDDEN = 'OT_TICKET_FORBIDDEN',

  // Leave
  LEAVE_NOT_FOUND = 'LEAVE_NOT_FOUND',
  LEAVE_INSUFFICIENT_BALANCE = 'LEAVE_INSUFFICIENT_BALANCE',
  LEAVE_OVERLAPPING = 'LEAVE_OVERLAPPING', // thêm: trùng lịch nghỉ
  LEAVE_INVALID_DATE_RANGE = 'LEAVE_INVALID_DATE_RANGE', // thêm: startDate > endDate
  LEAVE_INVALID_STATUS = 'LEAVE_INVALID_STATUS', // thêm: approve/reject sai status
  LEAVE_TYPE_NOT_FOUND = 'LEAVE_TYPE_NOT_FOUND', // thêm: không tìm thấy loại nghỉ phép

  // Department
  DEPARTMENT_NOT_FOUND = 'DEPARTMENT_NOT_FOUND',

  // Policy
  POLICY_NOT_FOUND = 'POLICY_NOT_FOUND',

  // File
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',

  // General
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  NOT_FOUND = 'NOT_FOUND',
}
